#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "200x"
author = "Raúl Ferrer"
recent_post_title = "Recent Posts"
# logo text will only show when logo is missing.
logo_text = "App{Codify}"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
image = "https://drive.google.com/uc?id=1fgY4h4t_CAiRmTKkd6t9BNGyO06NskU_"
title = "RaúlFerrer{Dev}"
description = "Become a Better Software Developer at Raúl Ferrer Dev."
# contact info
#address = "9567 Turner Trace Apt. BC C3G8A4"
#mobile = "+211234565523"
email = "developer.blog@icloud.com"
# contact form action
#contact_form_action = "#" # contact form works with https://formspree.io
# search
search = false

# featured post title
featured_post_title = "Featured Post"
mainSections = ["blog"]
# about widget content
about_widget_content = "I'm **Raúl Ferrer** a Mobile Tech Lead & iOS Engineer. I like to write and explain about everything I learn."
# promo widget content
promo_widget_title = "iOS Architecture Patterns"
promo_widget_subtitle = "Learn the **most on demand iOS Architectures**: MVC, MVP, MVVM, VIPER, and VIP."
promo_widget_image = "images/promo.png"
promo_widget_button = "I want to boost my career!"

# footer content
#footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "Copyright 2017-2023 Raúl Ferrer"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
#title_large = "**Code** Craftsmanship"
title_small = "**Become a Software Developer:** Tips, Tricks, and Resources for Success"
image = "images/youtube-call-to-action.png"
background_image = "/images/banner-bg-shape.svg"
#content = "A Developement Blog about iOS, Xcode, Swift, SwiftUI and Flutter. Learn how to build better applications."
#button_label = "Know About Me"
#button_link = "about/"

# Promo
[promo]
enable = true
#title_large = "iOS Architecture Patterns: MVC, MVP, MVVM, VIPER, and VIP in Swift"
title_small = "**iOS Architecture Patterns: MVC, MVP, MVVM, VIPER, and VIP in Swift**"
image = "images/promo.png"
content = "Ready to level up your iOS development skills? Look no further than **iOS Architecture Patterns: MVC, MVP, MVVM, VIPER, and VIP in Swift**. This comprehensive guide covers five of the most popular architecture patterns in the industry and how to implement them in your Swift projects. With clear explanations, code examples, and practical advice, you'll learn how to design and build iOS apps that are scalable, maintainable, and easy to test. Whether you're a beginner or an experienced developer, **iOS Architecture Patterns** will help you take your coding skills to new heights. Get your copy now and start building better apps with Swift today!"
button_label = "I want to boost my career!"
button_link = "https://www.amazon.com/iOS-Architecture-Patterns-VIPER-Swift/dp/1484290682/"

# Advertise
[[advertisement]]
image = "images/swiftui_course_row.png"
link = "swiftui-course/"

[[advertisement]]
image = "images/swift_tutorials_row.png"
link = "swift-tutorials/"

[[advertisement]]
image = "images/flutter_tutorials_row.png"
link = "flutter-tutorials/"

[[advertisement]]
image = "images/software_architecture_row.png"
link = "architecture/"

# cookies
[cookies]
enable = true
expire_days = 15
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["bookpromo", "sections", "about", "categories"]

# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "mail"
icon = "fas fa-envelope fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "mailto:developer.blog@icloud.com"

[[social]]
title = "twitter"
icon = "fab fa-twitter fa-lg" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/raulferrerdev"

#[[social]]
#title = "instagram"
#icon = "fab fa-instagram fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
#link = "https://www.instagram.com/raulferrerdev/"

[[social]]
title = "github"
icon = "fab fa-github fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/raulferrerdev"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://es.linkedin.com/in/raulferrergarcia"

[[social]]
title = "youtube"
icon = "fab fa-youtube fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/channel/UCnVlVlHwC_Mz-n3Kqy90SkQ?sub_confirmation=1"