#################### default parameters ################################
# favicon
favicon = "images/favicon.png"
# logo
logo = "images/logo.png"
# use `x` with logo_width, example: "100x".
# Note: logo_width is not work with .svg file
logo_width = "200x"
# logo text will only show when logo is missing.
logo_text = "App{Codify}"
# navbar fixed to top
navbar_fixed = true
# OpenGraph / Twitter Card metadata
description = "Become a Better Software Developer at AppCodify."
author = "Raúl Ferrer"
image = "images/twitter_card_promo.png?123" # this image will be used as fallback if a page has no image of its own
# contact info
#address = "9567 Turner Trace Apt. BC C3G8A4"
#mobile = "+211234565523"
email = "appcodify@icloud.com"
# contact form action
#contact_form_action = "#" # contact form works with https://formspree.io
# search
search = false

# featured post title
featured_post_title = "Featured Post"
recent_post_title = "Recent Post"
mainSections = ["blog"]
# about widget content
about_widget_content = "I'm **Raúl Ferrer** a Mobile Tech Lead & iOS Engineer. I like to write and explain about everthing I learn."
# footer content
#footer_content = "Lorem ipsum dolor sit amt, conse adip iscing. donec iaculis tempasus laoreet. Libero ullam rgscper."
# custom script on header, example: custom_script= "<script>console.log(\"Hello World\")</script>" 
custom_script= ""
# copyright
theme_copyright = true
copyright = "Copyright 2017-2023 Raúl Ferrer"

# Preloader
[preloader]
enable = false
preloader = "" # use jpg, png, svg or gif format.

# Banner
[banner]
enable = true
#title_large = "**Code** Craftsmanship"
title_small = "Become a **Better Developer** with my Blog and Tutorials"
image = "images/banner.png"
background_image = "/images/banner-bg-shape.svg"
#content = "A Developement Blog about iOS, Xcode, Swift, SwiftUI and Flutter. Learn how to build better applications."
button_label = "Know About Me"
button_link = "about/"

# Advertise
[[advertisement]]
image = "images/promotion.png"
link = "swiftui-course/"

# cookies
[cookies]
enable = true
expire_days = 2
content = "This site uses cookies. By continuing to use this website, you agree to their use."
button = "I Accept"

######################## sidebar widgets #########################
[widgets]
sidebar = ["about", "categories"] #, "recent-post", "newsletter"
# available widget : about,categories,newsletter,recent-post


# Subscription
[subscription]
enable = false
# mailchimp subsciption
mailchimp_form_action = "https://gmail.us4.list-manage.com/subscribe/post?u=463ee871f45d2d93748e77cad&amp;id=a0a2c6d074" # replace this url with yours
mailchimp_form_name = "b_463ee871f45d2d93748e77cad_a0a2c6d074" # replace this code with yours


############################# social site ########################
#[[social]]
#title = "facebook"
#icon = "fab fa-facebook" # themify icon : https://themify.me/themify-icons
#link = "#"

[[social]]
title = "mail"
icon = "fas fa-envelope fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "mailto:appcodify@icloud.com"

[[social]]
title = "twitter"
icon = "fab fa-twitter fa-lg" # themify icon : https://themify.me/themify-icons
link = "https://twitter.com/appcodify"

#[[social]]
#title = "instagram"
#icon = "fab fa-instagram fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
#link = "https://www.instagram.com/raulferrerdev/"

[[social]]
title = "github"
icon = "fab fa-github fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://github.com/raulferrerdev"

[[social]]
title = "linkedin"
icon = "fab fa-linkedin fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://es.linkedin.com/in/raulferrergarcia"

[[social]]
title = "youtube"
icon = "fab fa-youtube fa-lg" # fontawesome icon pack : https://fontawesome.com/icons/
link = "https://www.youtube.com/channel/UCnVlVlHwC_Mz-n3Kqy90SkQ?sub_confirmation=1"